*;
/*----G_CLUSTER_CODE begin----*/
length _NORM2 $ 2;
%DMNORMCP( CLUSTER_CODE , _NORM2 )
drop _NORM2;
select(_NORM2);
when(". " ) G_CLUSTER_CODE = 2;
when("01" ) G_CLUSTER_CODE = 1;
when("02" ) G_CLUSTER_CODE = 6;
when("03" ) G_CLUSTER_CODE = 1;
when("04" ) G_CLUSTER_CODE = 0;
when("05" ) G_CLUSTER_CODE = 4;
when("06" ) G_CLUSTER_CODE = 6;
when("07" ) G_CLUSTER_CODE = 6;
when("08" ) G_CLUSTER_CODE = 7;
when("09" ) G_CLUSTER_CODE = 4;
when("10" ) G_CLUSTER_CODE = 8;
when("11" ) G_CLUSTER_CODE = 3;
when("12" ) G_CLUSTER_CODE = 3;
when("13" ) G_CLUSTER_CODE = 1;
when("14" ) G_CLUSTER_CODE = 3;
when("15" ) G_CLUSTER_CODE = 4;
when("16" ) G_CLUSTER_CODE = 3;
when("17" ) G_CLUSTER_CODE = 6;
when("18" ) G_CLUSTER_CODE = 4;
when("19" ) G_CLUSTER_CODE = 3;
when("20" ) G_CLUSTER_CODE = 3;
when("21" ) G_CLUSTER_CODE = 7;
when("22" ) G_CLUSTER_CODE = 6;
when("23" ) G_CLUSTER_CODE = 5;
when("24" ) G_CLUSTER_CODE = 2;
when("25" ) G_CLUSTER_CODE = 4;
when("26" ) G_CLUSTER_CODE = 3;
when("27" ) G_CLUSTER_CODE = 5;
when("28" ) G_CLUSTER_CODE = 0;
when("29" ) G_CLUSTER_CODE = 6;
when("30" ) G_CLUSTER_CODE = 7;
when("31" ) G_CLUSTER_CODE = 4;
when("32" ) G_CLUSTER_CODE = 8;
when("33" ) G_CLUSTER_CODE = 7;
when("34" ) G_CLUSTER_CODE = 5;
when("35" ) G_CLUSTER_CODE = 3;
when("36" ) G_CLUSTER_CODE = 5;
when("37" ) G_CLUSTER_CODE = 6;
when("38" ) G_CLUSTER_CODE = 2;
when("39" ) G_CLUSTER_CODE = 5;
when("40" ) G_CLUSTER_CODE = 1;
when("41" ) G_CLUSTER_CODE = 6;
when("42" ) G_CLUSTER_CODE = 2;
when("43" ) G_CLUSTER_CODE = 6;
when("44" ) G_CLUSTER_CODE = 7;
when("45" ) G_CLUSTER_CODE = 7;
when("46" ) G_CLUSTER_CODE = 5;
when("47" ) G_CLUSTER_CODE = 6;
when("48" ) G_CLUSTER_CODE = 1;
when("49" ) G_CLUSTER_CODE = 6;
when("50" ) G_CLUSTER_CODE = 8;
when("51" ) G_CLUSTER_CODE = 6;
when("52" ) G_CLUSTER_CODE = 4;
when("53" ) G_CLUSTER_CODE = 2;
otherwise substr(_WARN_, 2, 1) = 'U';
end;
label G_CLUSTER_CODE="Grouped Levels for CLUSTER_CODE";
/*----G_CLUSTER_CODE end----*/
