label OPT_PER_CAPITA_INCOME = 'Transformed PER_CAPITA_INCOME';
length OPT_PER_CAPITA_INCOME $36;
if (PER_CAPITA_INCOME eq .) then OPT_PER_CAPITA_INCOME="01:low-14976, MISSING";
else
if (PER_CAPITA_INCOME < 14976) then
OPT_PER_CAPITA_INCOME = "01:low-14976, MISSING";
else
if (PER_CAPITA_INCOME >= 14976) then
OPT_PER_CAPITA_INCOME = "02:14976-high";
