label OPT_LIFETIME_GIFT_COUNT = 'Transformed LIFETIME_GIFT_COUNT';
length OPT_LIFETIME_GIFT_COUNT $36;
if (LIFETIME_GIFT_COUNT eq .) then OPT_LIFETIME_GIFT_COUNT="02:4.5-13.5, MISSING";
else
if (LIFETIME_GIFT_COUNT < 4.5) then
OPT_LIFETIME_GIFT_COUNT = "01:low-4.5";
else
if (LIFETIME_GIFT_COUNT >= 4.5 and LIFETIME_GIFT_COUNT < 13.5) then
OPT_LIFETIME_GIFT_COUNT = "02:4.5-13.5, MISSING";
else
if (LIFETIME_GIFT_COUNT >= 13.5) then
OPT_LIFETIME_GIFT_COUNT = "03:13.5-high";
