label OPT_RECENT_RESPONSE_PROP = 'Transformed RECENT_RESPONSE_PROP';
length OPT_RECENT_RESPONSE_PROP $36;
if (RECENT_RESPONSE_PROP eq .) then OPT_RECENT_RESPONSE_PROP="01:low-0.2125, MISSING";
else
if (RECENT_RESPONSE_PROP < 0.2125) then
OPT_RECENT_RESPONSE_PROP = "01:low-0.2125, MISSING";
else
if (RECENT_RESPONSE_PROP >= 0.2125) then
OPT_RECENT_RESPONSE_PROP = "02:0.2125-high";
