label OPT_MEDIAN_HOUSEHOLD_INCOME = 'Transformed MEDIAN_HOUSEHOLD_INCOME';
length OPT_MEDIAN_HOUSEHOLD_INCOME $36;
if (MEDIAN_HOUSEHOLD_INCOME eq .) then OPT_MEDIAN_HOUSEHOLD_INCOME="01:low-624.5, MISSING";
else
if (MEDIAN_HOUSEHOLD_INCOME < 624.5) then
OPT_MEDIAN_HOUSEHOLD_INCOME = "01:low-624.5, MISSING";
else
if (MEDIAN_HOUSEHOLD_INCOME >= 624.5) then
OPT_MEDIAN_HOUSEHOLD_INCOME = "02:624.5-high";
