label OPT_LIFETIME_CARD_PROM = 'Transformed LIFETIME_CARD_PROM';
length OPT_LIFETIME_CARD_PROM $36;
if (LIFETIME_CARD_PROM eq .) then OPT_LIFETIME_CARD_PROM="03:12.5-39.5, MISSING";
else
if (LIFETIME_CARD_PROM < 7.5) then
OPT_LIFETIME_CARD_PROM = "01:low-7.5";
else
if (LIFETIME_CARD_PROM >= 7.5 and LIFETIME_CARD_PROM < 12.5) then
OPT_LIFETIME_CARD_PROM = "02:7.5-12.5";
else
if (LIFETIME_CARD_PROM >= 12.5 and LIFETIME_CARD_PROM < 39.5) then
OPT_LIFETIME_CARD_PROM = "03:12.5-39.5, MISSING";
else
if (LIFETIME_CARD_PROM >= 39.5) then
OPT_LIFETIME_CARD_PROM = "04:39.5-high";
