label IMP_MONTHS_SINCE_LAST_PROM_RESP = 'Imputed MONTHS_SINCE_LAST_PROM_RESP';
IMP_MONTHS_SINCE_LAST_PROM_RESP = MONTHS_SINCE_LAST_PROM_RESP;
if missing(MONTHS_SINCE_LAST_PROM_RESP) then IMP_MONTHS_SINCE_LAST_PROM_RESP = 18;
