label M_MONTHS_SINCE_LAST_PROM_RESP = "Imputation Indicator for MONTHS_SINCE_LAST_PROM_RESP";
if missing(MONTHS_SINCE_LAST_PROM_RESP) then M_MONTHS_SINCE_LAST_PROM_RESP = 1;
else M_MONTHS_SINCE_LAST_PROM_RESP= 0;
